Repository innerstella/ES2024, pull requests merged in 2024-06, with the labels that each got.

#149 [황준용] week15
  Week15/Chapter40/준용.md
Labels: 준용

#147 [차수지] Week16
  Week15/Chapter40/수지.md
  Week16/Chapter41/수지.md
  Week16/Chapter42/수지.md
  Week16/Chapter43/수지.md
  Week16/Chapter44/수지.md
Labels: 수지

#151 [황준용] Week16
  Week16/Chapter41/준용.md
  Week16/Chapter42/준용.md
  Week16/Chapter43/준용.md
  Week16/Chapter44/준용.md
Labels: 준용

#153 [차수지] week 17
  Week17/Chapter45/수지.md
  Week17/Chapter46/수지.md
  Week17/Chapter47/수지.md
Labels: 수지

#154 [황준용] Week17
  Week17/Chapter45/준용.md
  Week17/Chapter46/준용.md
  Week17/Chapter47/준용.md
Labels: 준용

#155 [장연준] Week 17
  Week16/Chapter43/연준.md
  Week17/Chapter45/연준.md
  Week17/Chapter46/연준.md
  Week17/Chapter47/연준.md
Labels: 연준
